apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: eip-multi
spec:
  egressIPs:
  - "192.168.150.101"
  namespaceSelector:
    matchLabels:
      env: demo-multi
  podSelector:
    matchLabels:
      app: demo
  trafficSelector:
    matchLabels:
      traffic-group: multi-net
