apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo-eipt-secondary
  labels:
    app: demo
spec:
  terminationGracePeriodSeconds: 0
  nodeSelector:
    kubernetes.io/hostname: ovn-worker
  containers:
  - name: agnhost
    image: registry.k8s.io/e2e-test-images/agnhost:2.45
    command: ["/agnhost", "netexec", "--http-port=8080"]
